spring:
  profile:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_api
    username: root
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}



