spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinica_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

#esta ruta se dirige a la base de datos en memoria
## spring.datasource.url=jdbc:h2:mem:testdb
##spring.datasource.driverClassName=org.h2.Driver
## spring.datasource.username=sa
##spring.datasource.password=password
## spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
